# HSE 2021: Mathematical Methods of Data Analysis

## Seminar 1: Intro to Python for Data Analysis

**Author**: Polina Polunina

**tg**: @ppolunina

**25.01.2021**

<center> 
    <table>
        <tr>
            <th> Class Teachers </th>
            <th> Contact </th>
            <th> Group </th>
            <th> TA (contact) </th>
        </tr> 
        <tr><td> Maksim Karpov </td><td> tg: @buntar29 </td><td> БПИ181, БПИ182 </td><td> Victor Grishanin (tg: @vgrishanin), Kirill Bykov (tg: @darkydash) </td></tr>
        <tr><td> Vadim Kokhtev </td><td> tg: @despairazure </td><td> БПИ183 </td><td> Daniil Kosakin (tg: @nieto95) </td></tr>
        <tr><td> Maria Tikhonova </td><td> tg: @mashkka_t </td><td> БПИ184 </td><td> Alexandra Kogan (tg: @horror_in_black) </td></tr>
        <tr><td> Polina Polinuna </td><td> tg: @ppolunina </td><td> БПИ185 </td><td> Michail Kim (tg: @kimihailv) </td></tr>        
    </table>
</center>

**Today**:
- Jupyter, Colab, Anaconda
- Basic structures
- Functions & cycles
- Data manipulations with Numpy, Scipy, Pandas
- Data visualization with Matplotlib

**On top**:
- More detailed code notebooks to get acquainted with Python 

# Why Python

**Python** is an interpreted, high-level and general-purpose programming language. Python's design philosophy emphasizes code readability with its notable use of significant whitespace. (Wiki)

1) Open-source <br>
2) A lot of libraries, i.e. code for any specific problem 



# Jupyter Notebook

We are inside **Jupyter Notebook**. 

The <a href="https://jupyter.org/">Jupyter Notebook</a> is an open-source web application that allows you to create and share documents that contain live code, equations, visualizations and narrative text. Uses include: data cleaning and transformation, numerical simulation, statistical modeling, data visualization, machine learning, and much more.

The file we are working on now is called a **notebook**. Its standard extension is .ipynb, and it can be read and run through the Jupyter Notebook. But it can be downloaded as an html page or pdf document.

# Anaconda Distribution

<a href="https://www.anaconda.com/products/individual">Anaconda distribution</a> is a collection of data analysis tools in Python. It contains Jupyter Notebook, libraries for Python and other tools.

The most useful libraries:
 - <a href="http://numpy.org">Numpy</a> - is one of the main packages for scientific computing. It contains functionality for working with multidimensional arrays and high-level math functions.
 - <a href="http://numpy.org">SciPy</a> - scientific computing. Optimization methods, integration, signal and image processing modules, statistics, linear algebra, splines, clustering and much more.
 -  <a href="http://pandas.pydata.org/">Pandas</a> - a library for data processing and analysis. Designed for data of different nature - matrix, panel data, time series. Claims to be the most powerful and flexible analysis tool
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - implementation of machine learning and data mining methods with excellent documentation.
 - <a href="http://http://matplotlib.org/">Matplotlib</a> - library for data visualization, mainly 2D graphics.
 - <a href="https://pypi.org/project/seaborn/">Seaborn</a> - a data visualization library based on matplotlib. It provides a high-level interface for drawing attractive and informative statistical graphics

# How Jupyter Notebook Works

- Any notebook consists of **cells**. Even the current text is written in the cell. <br>

## New cell
- To create a new cell, you can use one of the following options: <br>
     1) use the "+" button on the top control panel; <br>
     2) press the letter "B" from the keyboard, and a new cell will appear after the current active one; <br>
     3) from the keyboard press the letter "A", and a new cell will appear before the current active one. <br>

## Cell types
- Two types of cells: <br>
     1) Code <br>
     2) Text <br> <br>
- Changing the type of a cell is carried out through the upper control panel, you should click on the cell and select its type

## Cell editing

- Cell that is not active is gray
- Cell is activated with one click of the cursor and turns blue
- The cell goes into editing mode by double clicking the cursor and turns green


## Interruption of work

Sometimes it is useful to stop a running cell.

- You can press the stop button when the active cell is running. STOP sign at the top.
- You can use the option in the Kernel menu - Interrupt
- You can radically "reboot" the laptop in the Kernel menu - Restart and Clear Output

# Google Colab
- <a href="https://colab.research.google.com/">Colab</a> is a Python development environment that runs in the browser using **Google Cloud**, i.e. you could work inside colab without installing python on your PC.
- Quick intro to Colab and Python <a href="https://colab.research.google.com/github/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l01c01_introduction_to_colab_and_python.ipynb">here</a>.


# Python for Data Analysis Basics 

For applied purposes, it is important to master several aspects:

- Standard language features
- Variables and data types
- Basic constructions
- Writing custom functions
- Loading and using libraries
- Data preprocessing and visualization

## Built-in Language Functions


### print()
Function for displaying content on the screen. <br>

**Required**: pass at least one object to be printed.

print(*objects, sep=' ', end='\n', file=sys.stdout, flush=False)¶

Optional keyword arguments:

- file :  a file-like object (stream); defaults to the current sys.stdout.

- sep:   string inserted between values, default a space.

- end:   string appended after the last value, default a newline.

- flush: whether to forcibly flush the stream.

In [1]:
print?

In [2]:
print(5)

5


In [3]:
print(5, 6, 7, 8)

5 6 7 8


In [4]:
print(5, 6, 7, 8, sep='_')

5_6_7_8


In [5]:
print('January')

January


#### Problem 1

Print "Hello, world!"

In [6]:
print('Hello, world!')

Hello, world!


In [7]:
input?

### input()
A function for entering data into the program from a keyboard. <br>
There are no required arguments. You can pass a string that will be displayed before the input cell.

In [8]:
name = input()
print(name)

Vadim
Vadim


And here a small transformation will allow you to display the desired text in front of the input cell

In [9]:
name = input('Input your name: ')
print(name)

Input your name: Vadim
Vadim


### Arithmetic operations
- Addition: +
- Subtraction: -
- Multiplication: *
- Division: /
- Exponentiation: **
- Integer division: //
- Remainder of the division: %

In [10]:
print('We are working with numbers', 5, 'and', 2)
print(5 + 2)
print(5 - 2)
print(5*2)
print(5 / 2)
print( 5 // 2)
print('The remainder of the division:', 5 % 2)
print('5 to power 2:', 5**2)

We are working with numbers 5 and 2
7
3
10
2.5
2
The remainder of the division: 1
5 to power 2: 25


#### Problem 2
Suppose that we have $100, that could be invested with 10% interest rate. <br>
How much money will we make in 7 years? Display the answer on the screen.

In [14]:
a = 1
1
# 100 * (1.1**7)

1

### Variables and variable types

The results of operations and manipulations sometimes need to be saved, so we define variables - named objects to which we assign values. 

In [15]:
savings_2017 = 2000
savings_2016 = 1800
increase = ((2000 - 1800) / 1800)*100

In [16]:
#Print % increase
print(round(increase), '%', sep='')

11%


#### Problem 3

Suppose that we have $100, that could be invested with 10% interest rate. <br>
How much money will we make in 7 years? Display the answer on the screen.

- Create a variable savings with a value of 100
- Create a variable rate that is responsible for the annual growth
- Store the calculation result in the result variable
- Print the results

A function **type** allows us to determine the type of a variable.

In [17]:
print(type(savings_2017))
print(type(increase))

<class 'int'>
<class 'float'>


In [18]:
text = 'Monatery Savings in 2017'
print(type(text))

<class 'str'>


In [19]:
x = False
print(type(x))

<class 'bool'>


If you need to change the type of a variable, then these functions are useful:

- int () - returns an integer variable
- float () - returns a non-integer variable
- bool () - returns a boolean variable
- str () - returns a string variable

In [20]:
print(savings_2017, type(savings_2017))
savings_2017_new = str(savings_2017)
print(savings_2017_new, type(savings_2017_new))
print('Savings ' +  'in 2017: ' + savings_2017_new)

2000 <class 'int'>
2000 <class 'str'>
Savings in 2017: 2000


In [21]:
print(int(savings_2017_new) - savings_2016)

200


#### Problem 4

Correct the code to make it work:

In [22]:
print("I started with $" + savings + " and now have $" + result + ". Not good!")

NameError: name 'savings' is not defined

### List

The four considered data types are designed so that one value is written in one variable:
- int: integer
- float: number with fractional part
- str: text
- bool: boolean variable

For example, if we want to record the savings of family members, we can create a number of variables and enter information there.

In [23]:
savings1 = 500
savings2 = 1000
savings3 = 746
savings4 = 456

But this is not convenient, so we could store all the information in one variable:

In [24]:
savings_family = [500, 1000, 746, 2000]

This build-in data structure is called a **list**.

In [25]:
savings_family = ['mom', 500,'dad', 1000, 'brother', 746, 'me', 2000]

Also you could create a **list of lists** :)

In [26]:
savings_family = [['mom', 500], ['dad', 1000], ['brother', 746], ['me', 2000]]

In [28]:
savings_family[1]

['dad', 1000]

In [29]:
s = 0
for member in savings_family:
    s = s + member[1]
print(s)

4246


In [30]:
print(savings_family)

[['mom', 500], ['dad', 1000], ['brother', 746], ['me', 2000]]


#### Problem 5

Create a list 'home' that stores names and footages of the rooms in the house. Print the list.

List elements can be accessed by index:

In [ ]:
savings_family[0]

In [ ]:
savings_family[0][1]

There are many methods (i.e. functions that are specific to lists) for working with lists:

Methods:
- **list.append(x)**	Add an item to the end of the list.
- **list.extend(L)**	Extend the list by appending all the items from the list L.
- **list.insert(i, x)**	Insert an item x at a given position i.
- **list.remove(x)**	Remove the first item from the list whose value is equal to x. ValueError, if there is no such item.
- **list.pop([i])**	Remove the item at the given position in the list, and return it. If no index is specified, a.pop() removes and returns the last item in the list.
- **list.index(x, [start [, end]])**	Return zero-based index in the list of the first item whose value is equal to x. Raises a ValueError if there is no such item.
- **list.count(x)**	Return the number of times x appears in the list.
- **list.sort([key=some_functions])**	Sort the items of the list in place based on some predefined function.
- **list.reverse()**	Reverse the elements of the list in place.
- **list.copy()**	Return a shallow copy of the list.
- **list.clear()**	Remove all items from the list.

In [31]:
# delete the last family member entry
savings_family.pop()
print(savings_family)

[['mom', 500], ['dad', 1000], ['brother', 746]]


In [32]:
# and now add
savings_family.append(['me', 2000])

In [33]:
# Create a two-list list that keeps track of your uncle's savings of 3000 and your aunt's of 10000
savings_relatives = [['uncle', 4000], ['aunt', 10000]]

In [34]:
savings_family.extend(savings_relatives)
print(savings_family)

[['mom', 500], ['dad', 1000], ['brother', 746], ['me', 2000], ['uncle', 4000], ['aunt', 10000]]


#### Problem 6

Calculate the total family savings

In [ ]:
for member in savings_family:
    ...
    print(member)

### Conditional statements

There are logical expressions that can be true or false. A simple boolean expression is  <br /> 

< arithmetic expression > < comparison sign > < arithmetic expression >. <br /> 

For example, if we have variables x and y with some values, then the logical expression <br /> x + y < 3y <br /> as the first arithmetic expression has x + y, as a comparison sign < (less than),and the second arithmetic expression is 3y.

<center> 
    <table>
        <tr>
            <th>Logical expression </th>
            <th> Value </th>
        </tr> 
        <tr><td>&lt;</td><td> Less than </td></tr>
        <tr><td>&gt;</td><td> Greater than</td></tr>
        <tr><td>&lt;=</td><td> Less or equal</td></tr>
        <tr><td>&gt;=</td><td> Greater or equal</td></tr>
        <tr><td>==</td><td> Equal </td></tr>
        <tr><td>!=</td><td> Not equal</td></tr>
    </table>
</center>

In [35]:
x = 1 > 2
print(type(x))
print(x)
print(int(x))

<class 'bool'>
False
0


To write a complex logical expression, it is often necessary to use logical connectives **and**, **or** and **not**. Operations **and** and **or** are binari operations, i.е. must be written between operands, for instance, **x < 3 or y > 2**. Operation **not** - unary and must be written before its only operand.

In [37]:
x = int(input())
y = int(input())
z = int(input())
print(x == y)
print(x > y and y < z)

10
10
20
True
False


#### Problem 7

Compare x with 10. Print the result

In [ ]:
x = 7


**Problem 8**

Does mom's savings fall in the range from 300 to 500? Write a boolean expression that tests this condition

In [ ]:
savings_mom = 500



### Conditional operator

The most common use of logical expressions is in conditional statements.

Python syntax: <br />
**if** condition_1:<br />
&emsp; commands<br />
**elif** condition_2:<br />
&emsp; commands<br />
**elif** condition_3:<br />
&emsp; commands<br />
**else**: <br />
&emsp; commands<br />

In [38]:
x = 5
y = 7
if x > y:
    print('X greater than Y')
    print(x - y)
else:
    print(' ')
    print('X less or equal to Y')

 
X less or equal to Y


In [39]:
x = int(input('Input X:'))
y = int(input('Input Y:'))
if x > y:
    print('X greater than Y')
    print(x - y)
elif y > x:
    print('Y greater than X')
    print(y - x)
else:
    print('X equal to Y')

Input X:10
Input Y:20
Y greater than X
10


#### Problems 9-10

1) You are given the area of the kitchen. If it exceeds 15 sq.m, then the line "The kitchen is large!" Should appear, otherwise - "The kitchen is small"

In [ ]:
room = "kit"
area = 14.0

if :
    print()
else:
    print()

2) Given a natural number, it is required to determine whether the year with the given number is a leap year. If the year is a leap year, then output YES, otherwise output NO. Recall that, according to the Gregorian calendar, a year is a leap year if its number is a multiple of 4, but not a multiple of 100, and also if it is a multiple of 400.

In [ ]:
n = int(input())
if :
    print('YES')
    
else:
    print('NO')

### Cycle while

As soon as a line of code has been executed, it is "forgotten"; to repeat this action, you must explicitly re-register. Cyclic constructs are used to repeat the same actions many times.

**While** allows you to execute commands as long as the condition is true. After the completion of the execution of the block of commands related to **while**, control returns to the line with the condition and, if it is satisfied, then the execution of the block of commands is repeated, and if not, execution of the commands written after **while** continues.

It's important not to accidentally loop endlessly!

**while** condition_1:<br />
&emsp; commands<br />


#### Problem 11

For a given integer N, print the squares of all numbers preceding N (including N) in descending order

**Example**

Input: <br />
3

Output: <br />
9<br />
4<br />
1<br />


## Cycle for

### Функция range(n)
An object of class range is created, inside which there is an arithmetic progression in the specified ranges and with a specific step

Its syntax:
- range(start, stop[, step])

In [41]:
print(range(5))
print(list(range(5)))
print(list(range(2, 7)))
print(list(range(2, 6, 2)))

range(0, 5)
[0, 1, 2, 3, 4]
[2, 3, 4, 5, 6]
[2, 4]


### Cycle for
The for loop lets you iterate through the elements from something iterable.

Its syntax: <br />
**for** i **in** range of change i:<br />
&emsp; commands

In [42]:
n = 5
for i in range(n + 1):
    print(i**2)

0
1
4
9
16
25


In [43]:
for color in ['red', 'green', 'yellow']:
    print(color, 'apple')

red apple
green apple
yellow apple


#### Problem 12

Print the total savings of all family members from the savings_family list using **for loop**

In [ ]:
savings_family

## Functional programming

If some operations need to be repeated from time to time and there are no built-in functions, then you can create your own.

Syntax: <br /> 
**def** function name(arguments):<br /> 
&emsp; commands<br /> 
&emsp; **return** the result <br /> 

The function must be written anywhere before its first call.

In [45]:
def power(number, p):
    result = number**p
    return result

number = int(input())
p = int(input())
print(power(number, p))

6
2
36


In [46]:
power(5, '2')

TypeError: unsupported operand type(s) for ** or pow(): 'int' and 'str'

In [ ]:
6**5

#### Problem 13

Write a function that calculates the area of a triangle by the length of all three sides. The sides are introduced outside the function. <br />
Hint: use Heron's formula
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$
**Example**

Input:<br />
3
4
5

Output: <br />
6

In [ ]:
def square_triangle(a, b, c):
    ...
    return 

In [ ]:
a = int(input())
b = int(input())
c = int(input())
print(square_triangle(a, b, c))

# Intro to Numpy

Library import:

In [47]:
import numpy as np

### 1. Numpy array structure np.ndarray

np.ndarray - it is an array containing elements **of the same type**.

It means that:

In [48]:
a = [2, 4, 5]
a

[2, 4, 5]

In [49]:
a_numpy = np.array(a)
a_numpy.dtype

dtype('int64')

In [50]:
b = [2, 3.14]
np.array(b)

array([2.  , 3.14])

In [51]:
c = [2, 3.14, 'kotiki']
np.array(c)

array(['2', '3.14', 'kotiki'], dtype='<U32')

In [52]:
my_list = [2, 4.14, 'kotiki', [2,3,4]]
my_list

[2, 4.14, 'kotiki', [2, 3, 4]]

In [53]:
# As object dtype
np.array([2, 4.14, 'kotiki', [2, 4, 5]], dtype='object')

array([2, 4.14, 'kotiki', list([2, 4, 5])], dtype=object)

### Indexing

In [54]:
a_numpy

array([2, 4, 5])

In [55]:
a_numpy[0]

2

In [56]:
a_numpy[1]

4

In [57]:
a_numpy[-1]

5

In [59]:
a_numpy[:-1]

array([2, 4])

In [60]:
a_numpy[1:4]

array([4, 5])

In [63]:
(a_numpy > 4)

array([False, False,  True])

In [64]:
(a_numpy < 6)

array([ True,  True,  True])

In [62]:
(a_numpy > 4) & (a_numpy < 6)

array([False, False,  True])

In [65]:
# subsampling an array with boolean conditions
a_numpy[(a_numpy > 4) & (a_numpy < 6)]

array([5])

In [66]:
a_numpy[a_numpy > 2]

array([4, 5])

### Built-in methods

to overview all available methods, after the dot (.) press "Tab"

In [ ]:
a_numpy

In [67]:
# sum of all array elements
a_numpy.sum()

11

In [68]:
# average of all array elements
a_numpy.mean()

3.6666666666666665

In [69]:
# maximum array element
a_numpy.max()

5

In [70]:
# minimum element of the array
a_numpy.min()

2

In [71]:
# result of multiplying all elements of the array
a_numpy.prod()

40

In [72]:
# array with strings
b = np.array(['Maria', 'Evgenii', 'Polina', 'Misha', 'Anya'])

In [73]:
# sort
b.sort()
b

array(['Anya', 'Evgenii', 'Maria', 'Misha', 'Polina'], dtype='<U7')

In [74]:
%%timeit
a_numpy.sum()

2.68 µs ± 240 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [75]:
%%timeit
a_numpy.mean()

7.99 µs ± 361 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
# measures the execution time of the entire cell

In [ ]:
%%timeit
a_numpy.sum()
a_numpy.mean()

In [ ]:
# Set parameters
## n - number of cycles
## m - number of iterations in one cycle

In [76]:
%%timeit -n 5 -r 10
a_numpy.sum()

3.28 µs ± 1.99 µs per loop (mean ± std. dev. of 10 runs, 5 loops each)


### Vectorized operations (no-cycle operations)

#### Example: elementwise addition of two one-dimensional arrays

In [77]:
# import the library
import numpy as np

# fix the random number generator
np.random.seed(42)

# create two numpy arrays
a_numpy = np.random.randint(low=1, high=10, size=5)
b_numpy = np.random.randint(low=1, high=10, size=5)
print('a_numpy: {}, b_numpy: {}, type: {}'.format(a_numpy, b_numpy, type(a_numpy)))

# create two similar lists
a_list = a_numpy.tolist()
b_list = b_numpy.tolist()
print('a_list: {}, b_list: {}, type: {}'.format(a_list, b_list, type(a_list)))

a_numpy: [7 4 8 5 7], b_numpy: [3 7 8 5 4], type: <class 'numpy.ndarray'>
a_list: [7, 4, 8, 5, 7], b_list: [3, 7, 8, 5, 4], type: <class 'list'>


pure python:

In [78]:
sum_arr=[]
for i in range(len(a_list)):
    sum_arr.append(a_list[i] + b_list[i])
print(sum_arr)

[10, 11, 16, 10, 11]


vectorized solution with numpy:

In [79]:
sum_numpy = a_numpy + b_numpy
print(sum_numpy)

[10 11 16 10 11]


In [80]:
%%timeit
sum_arr=[]
for i in range(len(a_list)):
    sum_arr.append(a_list[i] + b_list[i])

1.45 µs ± 77.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [81]:
%%timeit
sum_numpy = a_numpy + b_numpy

614 ns ± 30.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#### Computing the product of two matrices

In [82]:
import random

In [83]:
# an example of how else you can fix a random number generator
random.seed(42)

In [84]:
np.random.seed(42)

# create two numpy arrays
a_numpy = np.random.randint(low=1, high=10, size=(3,4))
b_numpy = np.random.randint(low=1, high=10, size=(4,3))
print('a_numpy: \n{}, \n\nb_numpy: \n{}, \n\ntype: {}'.format(a_numpy, b_numpy, type(a_numpy)))

# create two similar lists
a_list = a_numpy.tolist()
b_list = b_numpy.tolist()
print('\na_list: \n{}, \n\nb_list: \n{}, \n\ntype: {}'.format(a_list, b_list, type(a_list)))

a_numpy: 
[[7 4 8 5]
 [7 3 7 8]
 [5 4 8 8]], 

b_numpy: 
[[3 6 5]
 [2 8 6]
 [2 5 1]
 [6 9 1]], 

type: <class 'numpy.ndarray'>

a_list: 
[[7, 4, 8, 5], [7, 3, 7, 8], [5, 4, 8, 8]], 

b_list: 
[[3, 6, 5], [2, 8, 6], [2, 5, 1], [6, 9, 1]], 

type: <class 'list'>


* pure python

In [85]:
prod_arr = [[],[],[]]

for i in range(len(a_list)):
    for j in range(len(a_list)):
        sum_ = 0
        for k in range(len(b_list)):
            sum_ += a_list[i][k] * b_list[k][j]
        prod_arr[i].append(sum_)

In [86]:
print(prod_arr)

[[75, 159, 72], [89, 173, 68], [87, 174, 65]]


* vectorized solution with numpy

In [87]:
c = np.zeros((a_numpy.shape[0], b_numpy.shape[1]))
for i in range(a_numpy.shape[0]):
    for j in range(b_numpy.shape[1]):
        for s in range(a_numpy.shape[1]):
            c[i, j] += a_numpy[i, s] * b_numpy[s, j]

In [88]:
print(c)

[[ 75. 159.  72.]
 [ 89. 173.  68.]
 [ 87. 174.  65.]]


* built-in numpy method

In [89]:
a_numpy.dot(b_numpy)

array([[ 75, 159,  72],
       [ 89, 173,  68],
       [ 87, 174,  65]])

In [90]:
%%timeit -r 5
prod_arr = [[],[],[]]

for i in range(len(a_list)):
    for j in range(len(a_list)):
        sum_ = 0
        for k in range(len(b_list)):
            sum_ += a_list[i][k] * b_list[k][j]
        prod_arr[i].append(sum_)

14.6 µs ± 682 ns per loop (mean ± std. dev. of 5 runs, 100000 loops each)


In [91]:
%%timeit
c = np.zeros((a_numpy.shape[0], b_numpy.shape[1]))
for i in range(a_numpy.shape[0]):
    for j in range(b_numpy.shape[1]):
        for s in range(a_numpy.shape[1]):
            c[i, j] += a_numpy[i, s] * b_numpy[s, j]

51.5 µs ± 4.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [92]:
%%timeit
a_numpy.dot(b_numpy)

991 ns ± 48.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#### Example: Chaining Calculations

Given a functions

$f(x) = \frac{1}{2}x^TAx + b^Tx + c$

and its gradient

$\nabla{f(x)} = \frac{1}{2}(A + A^T)x + b$

calculate $f(x)$ and $\nabla{f(x)}$ at the given point $x$

In [93]:
np.random.seed(42)
A = np.random.randint(low=1, high=10, size=(3,3))
print(A)

[[7 4 8]
 [5 7 3]
 [7 8 5]]


In [94]:
x = np.random.randint(1,10,3)
b = np.random.randint(1,10,3)
c = np.random.randint(1,10,1)
print('x:', x)
print('b:', b)
print('c:', c)

x: [4 8 8]
b: [3 6 5]
c: [2]


In [95]:
0.5 * x.T.dot(A).dot(x) + b.T.dot(x) + c

array([1278.])

In [96]:
0.5 * (A + A.T).dot(x) + b

array([127., 124., 119.])

In [97]:
x.T @ (A)

array([124, 136,  96])

In [98]:
x.T.dot(A)

array([124, 136,  96])

# Intro to Pandas


In [100]:
import pandas as pd

There are two data structures in pandas:
- **Series**: a one-dimensional array with named indices (most often, data of the same type)
- **DataFrame**: two-dimensional array, has a tabular structure, is easily resizable, can contain data of different types

Both types can be created manually using functions from the library itself:
- pandas.Series(data=None, index=None, dtype=None)
- pandas.DataFrame(data=None, index=None, columns=None, dtype=None)

- **data** - data to be written to the structure
- **index** - row indices
- **columns** - column names
- **dtype** - data type

Besides **data**, other parameters are optional.


We can of course create the dataframes ourselves!

In [99]:
columns = ['country', 'province', 'region_1', 'region_2']
index = [0, 1, 10, 100]
data = [['Italy', 'Sicily & Sardinia', 'Etna', 'NaN'], 
        ['Portugal', 'Douro', 'NaN', 'NaN'],
       ['US', 'California', 'Napa Valley', 'Napa'],
       ['US', 'New York', 'Finger Lakes', 'Finger Lakes']]

Now let's put it into a dataframe

In [101]:
df = pd.DataFrame(data, columns = columns, index = index)
df

country           province      region_1      region_2
0       Italy  Sicily & Sardinia          Etna           NaN
1    Portugal              Douro           NaN           NaN
10         US         California   Napa Valley          Napa
100        US           New York  Finger Lakes  Finger Lakes

#### Pandas problem 1

Create pandas dataframe from the table below

<center> 
    <table>
        <tr>
            <th> Name </th>
            <th> Score </th>
            <th> Attempts </th>
            <th> Qualify </th>
        </tr> 
        <tr><td> Anastasia </td><td> 12.5 </td><td> 1 </td><td> Yes </td></tr>
        <tr><td> Dima </td><td> 9.0 </td><td> 3 </td><td> No </td></tr>
        <tr><td> Kate </td><td> 16.5 </td><td> 2 </td><td> Yes </td></tr>
        <tr><td> James </td><td> Nan </td><td> 3 </td><td> No </td></tr>
        <tr><td> Emily </td><td> 9.0 </td><td> 2 </td><td> No </td></tr>        
    </table>
</center>

### Loading and writing data

The truth is that we will not be so cruel to ourselves and will not manually enter data. We will load from a file.


- Functions of the common format **pd.read_format** и **pd.to_format**
read and write data, respectively. <br /> A complete list can be found in the documentation:
http://pandas.pydata.org/pandas-docs/stable/io.html


Let's learn how to read data in csv (comma separated value) format with the function:

- <a href="http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html#pandas.read_csv"> pd.read_csv()</a>: 

She has a lot of critical arguments:
 - **filepath_or_buffer** - text string with the name (address) of the file
 - **sep** - separator between data
 - **header** - the number of the line in which the column names are indicated in the file, None if not
 - **names** - a list with column names
 - **index_col** - a column number, or a list, or nothing - a column in the file to take the row names


We will work with Wine dataset. The name of the file is 'dpo_1-2_winemag-data_first150k.csv'

In [102]:
data = pd.read_csv('dpo_1-2_winemag-data_first150k.csv')

In [105]:
! head -2 dpo_1-2_winemag-data_first150k.csv

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,"This tremendous 100% varietal wine hails from Oakville and was aged over three years in oak. Juicy red-cherry fruit and a compelling hint of caramel greet the palate, framed by elegant, fine tannins and a subtle minty tone in the background. Balanced and rewarding from start to finish, it has years ahead of it to develop further nuance. Enjoy 2022–2030.",Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz



### See what's loaded

In [106]:
data.head(5)

Unnamed: 0 country                                        description  \
0           0      US  This tremendous 100% varietal wine hails from ...   
1           1   Spain  Ripe aromas of fig, blackberry and cassis are ...   
2           2      US  Mac Watson honors the memory of a wine once ma...   
3           3      US  This spent 20 months in 30% new French oak, an...   
4           4  France  This is the top wine from La Bégude, named aft...   

                            designation  points  price        province  \
0                     Martha's Vineyard      96  235.0      California   
1  Carodorum Selección Especial Reserva      96  110.0  Northern Spain   
2         Special Selected Late Harvest      96   90.0      California   
3                               Reserve      96   65.0          Oregon   
4                            La Brûlade      95   66.0        Provence   

            region_1           region_2             variety  \
0        Napa Valley               Napa  Cabernet Sauvignon   
1               Toro                NaN       Tinta de Toro   
2     Knights Valley             Sonoma     Sauvignon Blanc   
3  Willamette Valley  Willamette Valley          Pinot Noir   
4             Bandol                NaN  Provence red blend   

                    winery  
0                    Heitz  
1  Bodega Carmen Rodríguez  
2                 Macauley  
3                    Ponzi  
4     Domaine de la Bégude

There is something wrong with the first column, let's fix it 

In [107]:
data = pd.read_csv('dpo_1-2_winemag-data_first150k.csv', index_col = 0)

In [108]:
data.head(3)

country                                        description  \
0      US  This tremendous 100% varietal wine hails from ...   
1   Spain  Ripe aromas of fig, blackberry and cassis are ...   
2      US  Mac Watson honors the memory of a wine once ma...   

                            designation  points  price        province  \
0                     Martha's Vineyard      96  235.0      California   
1  Carodorum Selección Especial Reserva      96  110.0  Northern Spain   
2         Special Selected Late Harvest      96   90.0      California   

         region_1 region_2             variety                   winery  
0     Napa Valley     Napa  Cabernet Sauvignon                    Heitz  
1            Toro      NaN       Tinta de Toro  Bodega Carmen Rodríguez  
2  Knights Valley   Sonoma     Sauvignon Blanc                 Macauley

### Let's see what has loaded:

- Let's count the number of entries
- Let's check the data types
- Check if there are gaps in the data

Let's count how many records are in the data.

- The **count ()** method helps

In [109]:
data.count()

country        150925
description    150930
designation    105195
points         150930
price          137235
province       150925
region_1       125870
region_2        60953
variety        150930
winery         150930
dtype: int64

- The **info()** method also shows what type of data is in the columns

In [110]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150930 entries, 0 to 150929
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   country      150925 non-null  object 
 1   description  150930 non-null  object 
 2   designation  105195 non-null  object 
 3   points       150930 non-null  int64  
 4   price        137235 non-null  float64
 5   province     150925 non-null  object 
 6   region_1     125870 non-null  object 
 7   region_2     60953 non-null   object 
 8   variety      150930 non-null  object 
 9   winery       150930 non-null  object 
dtypes: float64(1), int64(1), object(8)
memory usage: 12.7+ MB


In [111]:
data.dtypes

country         object
description     object
designation     object
points           int64
price          float64
province        object
region_1        object
region_2        object
variety         object
winery          object
dtype: object

Let's start checking for gaps!

- **.isnull ()** - produces a table, where False - the cell is full, True - the cell is empty :( Closest relatives - isna ()

In [112]:
data.isnull()

country  description  designation  points  price  province  region_1  \
0         False        False        False   False  False     False     False   
1         False        False        False   False  False     False     False   
2         False        False        False   False  False     False     False   
3         False        False        False   False  False     False     False   
4         False        False        False   False  False     False     False   
...         ...          ...          ...     ...    ...       ...       ...   
150925    False        False         True   False  False     False     False   
150926    False        False        False   False  False     False     False   
150927    False        False        False   False  False     False     False   
150928    False        False        False   False  False     False     False   
150929    False        False         True   False  False     False     False   

        region_2  variety  winery  
0          False    False   False  
1           True    False   False  
2          False    False   False  
3          False    False   False  
4           True    False   False  
...          ...      ...     ...  
150925      True    False   False  
150926      True    False   False  
150927      True    False   False  
150928      True    False   False  
150929      True    False   False  

[150930 rows x 10 columns]

Let me get ahead of the story and show you how to visually assess the scale of a disaster :)

In [113]:
import matplotlib.pyplot as plt
import seaborn as sns

fig, ax = plt.subplots(figsize=(20,12))
sns_heatmap = sns.heatmap(data.isnull(), yticklabels=False, cbar=False, cmap='viridis')
plt.show()

ModuleNotFoundError: No module named 'seaborn'

What we could do?

There is not much choice: <br>

1) Delete: 
- dropna(axis=0, how='any'): axis = 0 - delete line, axis = 1 drop the column; how = 'any' - drop if there is at least one empty cell. how = 'all' - drop if there is a completely empty row or column

2) Fill in the gaps:
- fillna() - an art of fill in the gaps (will be discussed later in the course)


### Descriptive statistics

Now let's see what we have.

We will calculate the main descriptive statistics. All at once :)

- describe() - a method that returns a table with descriptive statistics. In this form, it counts everything for numeric columns

In [114]:
data.describe()

points          price
count  150930.000000  137235.000000
mean       87.888418      33.131482
std         3.222392      36.322536
min        80.000000       4.000000
25%        86.000000      16.000000
50%        88.000000      24.000000
75%        90.000000      40.000000
max       100.000000    2300.000000

A bit of magic, and non-numeric data will also have its descriptive statistics.

In [115]:
data.describe(include=['O'])

country                                        description designation  \
count   150925                                             150930      105195   
unique      48                                              97821       30621   
top         US  92-94 Barrel sample. A rounded wine, its tanni...     Reserve   
freq     62397                                                  6        2752   

          province     region_1       region_2     variety           winery  
count       150925       125870          60953      150930           150930  
unique         455         1236             18         632            14810  
top     California  Napa Valley  Central Coast  Chardonnay  Williams Selyem  
freq         44508         6209          13057       14482              374

In general, everything can be calculated for individual columns.

But we haven't learned how to select columns. Well, time for action.

### Data slices

Let's say we don't need a dataset, but only specific columns or rows or columns and rows.


How?

Remember that:
- the columns have names
- the rows have names
- if there are no names, then there are always their indexes

Based on this idea, we will start slicing data.

In [116]:
data.head(1)

country                                        description  \
0      US  This tremendous 100% varietal wine hails from ...   

         designation  points  price    province     region_1 region_2  \
0  Martha's Vineyard      96  235.0  California  Napa Valley     Napa   

              variety winery  
0  Cabernet Sauvignon  Heitz

####  Select by columns. Version 1.

In [119]:
type(data['price'])

pandas.core.series.Series

In [120]:
type(data[['price','country']])

pandas.core.frame.DataFrame

#### Select by rows. Version 1.


In [121]:
data[0:1]

country                                        description  \
0      US  This tremendous 100% varietal wine hails from ...   

         designation  points  price    province     region_1 region_2  \
0  Martha's Vineyard      96  235.0  California  Napa Valley     Napa   

              variety winery  
0  Cabernet Sauvignon  Heitz

In [122]:
data[:1]

country                                        description  \
0      US  This tremendous 100% varietal wine hails from ...   

         designation  points  price    province     region_1 region_2  \
0  Martha's Vineyard      96  235.0  California  Napa Valley     Napa   

              variety winery  
0  Cabernet Sauvignon  Heitz

#### Select by columns. Version 2. Still by names

In [123]:
data.loc[:, ['price']]

price
0       235.0
1       110.0
2        90.0
3        65.0
4        66.0
...       ...
150925   20.0
150926   27.0
150927   20.0
150928   52.0
150929   15.0

[150930 rows x 1 columns]

#### Select by rows. Version 2. Still by names

In [124]:
data.loc[0,:]

country                                                       US
description    This tremendous 100% varietal wine hails from ...
designation                                    Martha's Vineyard
points                                                        96
price                                                        235
province                                              California
region_1                                             Napa Valley
region_2                                                    Napa
variety                                       Cabernet Sauvignon
winery                                                     Heitz
Name: 0, dtype: object

#### Select by rows and columns #1

In [125]:
data.loc[0:5,['price', 'country']]

price country
0  235.0      US
1  110.0   Spain
2   90.0      US
3   65.0      US
4   66.0  France
5   73.0   Spain

#### Select by rows and columns #2. By rows and columns indexes

In [ ]:
data.iloc[2:5, [5,7]]

#### Pandas problem 2

Select the first line from the dataset (you have created it in the first task)

#### Pandas problem 3

Slice the data (by row indexes)

### Selection with conditions

So, what if I need wines over $ 15 dollars?

In [ ]:
# set a mask
mask = data['price'] > 15

In [ ]:
# select the required data

temp = data[mask]
temp

### Let's look at the data again! By plots :-) 

We reduce stress and do not go to get acquainted with libraries for visualization, because ...

The pandas library has a drawing tool!

- df.plot() - method for plotting

Let's try to just call it without everything and see what happens.

In [ ]:
data.plot()

Satisfied? Not really.

In [ ]:
data['price'].plot()

In [ ]:
data['points'].plot()

Something is gping wrong. Let's try to achieve some sensible visualization of the **points** column.

In [ ]:
data['points'].value_counts().plot(kind='bar')

What is **value_counts()**? (Without it, I do not advise you to run the code above, it will hurt)

In [ ]:
data['points'].value_counts()

In [ ]:
data['points'].value_counts().plot(kind='barh')

In [ ]:
data['points'].value_counts().plot(kind='line')

Again, not very good. Because our indexes are not sorted at value_counts ()!

Let's fix

In [ ]:
data['points'].value_counts().sort_index().plot(kind='line')

In [ ]:
data['points'].value_counts().sort_index().plot(kind='area')

In [ ]:
data['points'].sort_index().plot(kind='hist')

In [ ]:
data['points'].plot(kind='box')

Okay, we are done with one-column plots. And what about several columns?

In [ ]:
data.plot(kind ='box')

In [ ]:
data.plot(kind='box', subplots=True)

How are prices and sommelier ratings jointly distributed?

In [ ]:
 data.plot(x='points', y='price', kind='scatter')

In [ ]:
wine_counts = pd.read_csv('dpo_1-2_top-five-wine-score-counts.csv')
wine_counts.head(3)

In [ ]:
wine_counts.plot.line(x='points')

In [ ]:
wine_counts.plot.area(x='points')

In [ ]:
wine_counts.plot.bar(x='points', stacked=True)

# A bit more Visualization or Intro to matplotlib

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

Drawing the plot "by default":

In [ ]:
# create some synthetic data
import numpy as np
x = np.linspace(0,15,100)
# make a default plot
plt.plot(x)

In [ ]:
# default plot #2
y = np.cos(x)
plt.plot(y)

Whats wrong with the plot above?

* missing axes labels
* no plot title

Let's fix this:

In [ ]:
plt.plot(x, y)
plt.title('cos(x)')
plt.xlabel('х')
plt.ylabel('y')
plt.show()

Add labels to the plot:

In [ ]:
z = 0.5 * np.sin(x)

# make a plot
plt.plot(x, y, label='cos(x)')
plt.plot(x, z, label='sin(x)')
plt.title('0.5 sin(x) и cos(x)')
plt.xlabel('х')
plt.ylabel('y, z')
plt.legend()
plt.show()

Anyway something is going wrong! what?

Lets change the size of the plot:

In [ ]:
# make a plot
plt.figure(figsize=(8,4))
plt.plot(x, y, label='cos(x)')
plt.plot(x, z, label='sin(x)')
plt.title('0.5 sin(x) и cos(x)')
plt.xlabel('х')
plt.ylabel('y, z')
plt.legend()
plt.show()

How to change colors?

In [ ]:
# make a plot
plt.figure(figsize=(15,6))
plt.plot(x, y, label='cos(x)', c='g')
plt.plot(x, z, label='sin(x)', c='r')
plt.title('0.5 sin(x) и cos(x)')
plt.xlabel('х')
plt.ylabel('y, z')
plt.legend()
plt.show()

Multiple plots in the same axes

In [ ]:
plt.figure(1, figsize=(10,5))

plt.subplot(211)
plt.title('Two plots with joint x axis')
plt.plot(x, y, 'b-.', label='cos(x)')
plt.legend()

plt.subplot(212)
plt.plot(x, z, 'r--', label='0.5 sin(x)')
plt.xlabel('Joint axis х')
plt.legend()

plt.show()

### Bar plot

More code examples:
https://matplotlib.org/api/_as_gen/matplotlib.pyplot.bar.html#matplotlib.pyplot.bar

In [ ]:
x = np.arange(5)
height = [20, 23, 25, 24, 26]

plt.bar(x, height, align='center', color='c', linewidth = 100)

plt.title('Monthly Sales of Х')

plt.ylabel('mln USD')
plt.xticks(x, ('January', 'February', 'March', 'April', 'May'))

plt.show()

### Histogram

More code examples:

https://matplotlib.org/api/_as_gen/matplotlib.pyplot.hist.html

In [ ]:
np.random.seed(42)
x = np.random.normal(0, 1, 100000)


plt.hist(x, bins=10)
plt.title('Distribution of values in the X array')
plt.show()